"""""""""""""""""""""""""""""
" General
"""""""""""""""""""""""""""""

" Remove vi compatibility
set nocompatible

" Automatically reload a file when it changes
set autoread

" Enable file type, plugin and indentation files
filetype plugin indent on


"""""""""""""""""""""""""""""
" VIM User Interface
"""""""""""""""""""""""""""""

" Set scrolloff so lines are visible
" below/above the cursor
set so=7

" Turn on the WiLd menu
set wildmenu

" Ignore compiled files in wildmenu
set wildignore=*.o,*~,*.pyc,*.swp

" Ignore swap files in netwr
let g:netrw_list_hide='.*\.swp$'

" Show the current position
set ruler

" Show line numbers
set number

" Ignore case while searching
set ignorecase

" Use smartcase for searching
set smartcase

" Highlight search results
set hlsearch

" Highlight current search result
set incsearch

" Show matching brackets
set showmatch

" Blink matching brackets for
" this many thenths of a second
set mat=2


"""""""""""""""""""""""""""""
" Colors and Themes
"""""""""""""""""""""""""""""

" Enable syntax highlight
syntax enable

" Set vim to use 256 colors
set t_Co=256

" Color fix for Solarized in terminal mode
let g:solarized_termcolors=256

" Set special characters visibility
let g:solarized_visibility="low"

" Backgound color
set background=dark

" Set colorscheme
colorscheme solarized


"""""""""""""""""""""""""""""
" Text, Tab and Indent
"""""""""""""""""""""""""""""

" Always use UTF-8 encoding
set encoding=utf8

" Use smart tabs
set smarttab

" Use indent from previous line
set autoindent

" Recognize C syntax to add/remove indents
set smartindent

" Enable word wrapping
set wrap

" Set tab size
set tabstop=4
set softtabstop=4
set shiftwidth=4

" Use tabs, not spaces
set noexpandtab

" Show special characters by default
set list

" Change tab and end-of-line characters
set listchars=tab:▸\ ,eol:¬

"Invisible character colors 
"highlight NonText guifg=#4a4a59
"highlight SpecialKey guifg=#4a4a59


"""""""""""""""""""""""""""""
" Status line
"""""""""""""""""""""""""""""

" Always show the status line
set laststatus=2

" Status line formatting
set statusline=
set statusline+=%y		" File type
set statusline+=%.20F	" Full path to the file
set statusline+=%m		" Modified flag
set statusline+=%=		" Switch to right side
set statusline+=%l		" Current line
set statusline+=/		" Separator
set statusline+=%L		" Total lines
set statusline+=%4v		" Virtual column number
set statusline+=%4p%%	" Percentage through file
