#!/usr/bin/env bash
# bash prompt

# title
PS1="\[\e]0;\u@\h: \w\a\]"  # user@host: dir

# prompt
PS1+="\[\e[1;32m\]\u"       # username
PS1+="@"                    # @
PS1+="\h"                   # host
PS1+="\[\e[0m\]:"           # :
PS1+="\[\e[1;34m\]\w"       # working dir (full path)
PS1+="\n"
PS1+="\[\e[0m\]\$"          # $
